sonar.projectKey=ramirofd_ion-core
sonar.organization=ramirofd
sonar.projectName=ion-core
sonar.sources=src,inc
sonar.tests=tests
sonar.test.inclusions=tests/**/*
sonar.exclusions=bin/**,lib/**,man/**,src/man/**,tests/progress,tests/output/**,tests/log/**,host*_testdir/**,.scannerwork/**,.sonar/**
sonar.cfamily.compile-commands=.sonar/build-wrapper/compile_commands.json
sonar.cfamily.cobertura.reportPaths=.sonar/coverage.xml
sonar.scm.provider=git
